### ISSUE TITLE
Add more unique ways to print helloworld

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [Dimas-Saputra-Me/101-ways-to-print-helloworld#19]
# unique-ways-list

List of unique ways to print helloworld you can implement:
- [ ] Using ASCII values to represent each character.
- [ ] Printing "Hello, World!" with hexadecimal escape sequences.
- [ ] Printing "Hello, World!" in binary representation.
- [ ] Printing "Hello, World!" in Morse code.
- [ ] Printing "Hello, World!" with randomizer character combination.
- [ ] Printing "Hello, World!" with emojis
- [ ] Printing "Hello, World!" ssing QR Code translation
- [ ] (Any unique ways to print helloworld are open)

Another note that this repository isn't a repository of collection to print hello world in different languages, but collection of print hello world in unique ways like stated above

**Comment by udayprakash999** [comment]
ooo okay interesting
