### ISSUE TITLE
Add more ways to print "Hello World!"

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [Dimas-Saputra-Me/101-ways-to-print-helloworld#2]
Add more way to print "Hello World!" inside the [./code/ ](https://github.com/Dimas-Saputra-Me/101-ways-to-print-helloworld/tree/master/code) folder file (currently available in javascript language only).
Don't forget to read the guidelines before making a pull-request, Happy contributing.

**\~THANK YOU\~**

**Comment by arthurmatthew** [comment]
I'll work on this!

**Comment by yogitha02** [comment]
@Dimas-Saputra-Me Can i work on this

**Comment by Dimas-Saputra-Me** [comment]
Thank you for the contribution on this pull request #8 @yogitha02

**Comment by Madhur-Jatiya** [comment]
can I make a program of hello world in another language like java c c++ also??
