### ISSUE TITLE
Make another programming language suitable to run

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [Dimas-Saputra-Me/101-ways-to-print-helloworld#3]
## Issue
This repository only available to run Javascript file only inside the ./code/ folder, I wanted to make another folder (with another programming language name) and it suitable (can randomly get run by the main random function in [index.js](https://github.com/Dimas-Saputra-Me/101-ways-to-print-helloworld/blob/master/index.js))

## Things-To-Do
Make sure you do the step in the in order
1. Make it suitable (run-able) from the main index.js file
2. Create a new folder in the root folder with another programming language name
3. Create a new template.(extension) file in the root folder

### Programming-Language-To-Do
- [x] Javascript
- [x] C
- [x] C++
- [x] Go
- [x] Java
- [x] PHP
- [x] Python
- [ ] (Any programming language suggestions are open)

**Comment by arthurmatthew** [comment]
Hey, could I work on this? I can help create a new folder and I could also work on making `index.js` file work.

**Comment by Dimas-Saputra-Me** [comment]
Issue solved, Thank you @arthurmatthew for the contribution.
But anyone can still add more programming language to make it "run-able" from the index.js file, thank you.
